/**
 * Jitsi Configuration
 * Choose between free Jitsi (meet.jit.si) or JaaS (8x8.vc premium)
 */

export const jitsiConfig = {
  // Use JaaS (8x8.vc) premium service or free meet.jit.si
  useJaaS: true, // Set to true for premium 8x8.vc, false for free meet.jit.si

  // JaaS Configuration (Premium 8x8.vc)
  jaas: {
    appId: "vpaas-magic-cookie-06fa758e7c18435681a16b81d4c43676",
    domain: "8x8.vc",
  },

  // Free Jitsi Configuration
  free: {
    domain: "meet.jit.si",
  },

  // JWT Configuration (for premium features like recording)
  jwt: {
    enabled: false, // Set to true to enable JWT
    // JWT will be generated by backend if enabled
  },
};

/**
 * Get Jitsi domain based on configuration
 */
export const getJitsiDomain = () => {
  return jitsiConfig.useJaaS
    ? jitsiConfig.jaas.domain
    : jitsiConfig.free.domain;
};

/**
 * Get JaaS script URL
 */
export const getJitsiScriptUrl = () => {
  if (jitsiConfig.useJaaS) {
    return `https://${jitsiConfig.jaas.domain}/${jitsiConfig.jaas.appId}/external_api.js`;
  }
  return `https://${jitsiConfig.free.domain}/external_api.js`;
};

/**
 * Get room name with JaaS prefix if needed
 */
export const formatRoomName = (roomName) => {
  if (jitsiConfig.useJaaS) {
    return `${jitsiConfig.jaas.appId}/${roomName}`;
  }
  return roomName;
};
